<?php

namespace App\Http\Controllers\Auth;

use App\Exceptions\UserNotFoundException;
use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;

class SupportPasswordResetController extends Controller
{
    /**
     * Generate reset token for a user (called by support team)
     */
    public function __invoke(Request $request)
    {
        $request->validate([
            'user_id' => 'required|exists:users,id',
        ]);

        $user = User::find($request->user_id);

        if (!$user) {
            throw new UserNotFoundException();
        }

        // Delete all existing reset tokens for this user
        $user->resetPasswordTokens()->delete();

        // Generate a new unique token
        $token = $user->resetPasswordTokens()->create([
            'token' => Str::upper(Str::random(32)), // Token mais longo e seguro
        ]);

        Log::info('Password reset token generated by support', [
            'user_id' => $user->id,
            'user_email' => $user->email,
            'reset_by' => auth()->user()->email,
            'token' => $token->token,
        ]);

        // Generate reset URL using frontend URL
        $frontUrl = config('app.front_url', 'http://localhost:5174');
        $resetUrl = rtrim($frontUrl, '/') . "/reset-password-by-token/{$token->token}";

        return response()->json([
            'message' => "Token de reset gerado com sucesso para o usuário {$user->email}.",
            'user_email' => $user->email,
            'user_name' => $user->first_name . ' ' . $user->last_name,
            'reset_token' => $token->token,
            'reset_url' => $resetUrl,
        ], 200);
    }
}

